services:
    kelp.user.search_dto.factory:
        class: Kelp\AppBundle\Factory\SearchUserDTOFactory
        public: false

    kelp.type_storage.search_dto.factory:
        class: Kelp\AppBundle\Factory\SearchTypeStorageDTOFactory
        public: false

    kelp.type_storage.dto.factory:
        class: Kelp\AppBundle\Factory\TypeStorageDTOFactory
        public: false