services:
    kelp.type_storage.factory:
        class: Kelp\AppBundle\Factory\TypeStorageFactory
        public: false

    kelp.user_type_storage.factory:
        class: Kelp\AppBundle\Factory\TypeStorageFactory
        public: false

    kelp.storage.factory:
        class: Kelp\AppBundle\Factory\StorageFactory
        public: false