services:
    kelp.user.search_dto.factory:
        class: Kelp\AppBundle\Factory\SearchUserDTOFactory
        public: false

    kelp.type_storage.search_dto.factory:
        class: Kelp\AppBundle\Factory\SearchTypeStorageDTOFactory
        public: false

    kelp.type_storage.dto.factory:
        class: Kelp\AppBundle\Factory\TypeStorageDTOFactory
        public: false

    kelp.type_storage.factory:
        class: Kelp\AppBundle\Factory\TypeStorageFactory
        public: false

    kelp.user_type_storage.factory:
        class: Kelp\AppBundle\Factory\TypeStorageFactory
        public: false

    kelp.user_type_storage.dto.factory:
        class: Kelp\AppBundle\Factory\UserTypeStorageDTOFactory
        public: false