services:
    kelp.user.factory:
        class: Kelp\AppBundle\Factory\UserFactory
        public: false
    kelp.user.search_dto.factory:
        class: Kelp\AppBundle\Factory\SearchUserDTOFactory
        public: false

    kelp.type_storage.search_dto.factory:
        class: Kelp\AppBundle\Factory\SearchTypeStorageDTOFactory
        public: false