services:
    kelp.user.search_form.listener:
            class: Kelp\AppBundle\EventListener\SearchUserFormListener
            arguments:
              - "@kelp.user.search_dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('user')"
              - "@=service('request_stack').getCurrentRequest()"

    kelp.type_storage.search_form.listener:
            class: Kelp\AppBundle\EventListener\SearchTypeStorageFormListener
            arguments:
              - "@kelp.user.search_dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"
