services:
    kelp.user.search_form.listener:
            class: Kelp\AppBundle\EventListener\SearchUserFormListener
            arguments:
              - "@kelp.user.search_dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('user')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"
              - "@table_action.helper"


    kelp.type_storage.search_form.listener:
            class: Kelp\AppBundle\EventListener\SearchTypeStorageFormListener
            arguments:
              - "@kelp.type_storage.search_dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"
              - "@table_action.helper"


    kelp.type_storage.add_form.listener:
            class: Kelp\AppBundle\EventListener\AddTypeStorageFormListener
            arguments:
              - "@kelp.type_storage.dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"
              - "@table_action.helper"

    kelp.storage.add_form.listener:
            class: Kelp\AppBundle\EventListener\AddStorageFormListener
            arguments:
              - "@kelp.storage.dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('storage')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"
              - "@table_action.helper"

    kelp.type_storage.edit_form.listener:
            class: Kelp\AppBundle\EventListener\EditTypeStorageFormListener
            arguments:
              - "@kelp.type_storage.dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"
              - "@table_action.helper"


    kelp.type_storage.delete.listener:
            class: Kelp\AppBundle\EventListener\DeleteListener
            arguments:
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"

    kelp.user.delete.listener:
            class: Kelp\AppBundle\EventListener\DeleteListener
            arguments:
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('user')"
              - "@=service('request_stack').getCurrentRequest()"


    kelp.type_storage.find.listener:
            class: Kelp\AppBundle\EventListener\FindListener
            arguments:
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@serializer"

    kelp.user.find.listener:
            class: Kelp\AppBundle\EventListener\FindListener
            arguments:
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('user')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@serializer"

    kelp.dashboard.listener:
            class: Kelp\AppBundle\EventListener\DashboardListener
            arguments:
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('user')"
              - "@=service('request_stack').getCurrentRequest()"
              - null
              - "@=service('security.token_storage').getToken().getUser()"

    kelp.user_type_storage.edit_form.listener:
            class: Kelp\AppBundle\EventListener\EditUserTypeStorageFormListener
            arguments:
              - "@kelp.user_type_storage.dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('user')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"

    kelp.storage.delete.listener:
            class: Kelp\AppBundle\EventListener\DeleteListener
            arguments:
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('storage')"
              - "@=service('request_stack').getCurrentRequest()"

    kelp.storage.edit_form.listener:
            class: Kelp\AppBundle\EventListener\EditStorageFormListener
            arguments:
              - "@kelp.storage.dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('storage')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"