services:
    kelp.user.search_form.listener:
            class: Kelp\AppBundle\EventListener\SearchUserFormListener
            arguments:
              - "@kelp.user.search_dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('user')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"
              - "@table_action.helper"


    kelp.type_storage.search_form.listener:
            class: Kelp\AppBundle\EventListener\SearchTypeStorageFormListener
            arguments:
              - "@kelp.type_storage.search_dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"
              - "@table_action.helper"


    kelp.type_storage.add_form.listener:
            class: Kelp\AppBundle\EventListener\AddTypeStorageFormListener
            arguments:
              - "@kelp.type_storage.dto.factory"
              - "@form.factory"
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"
              - "@form_error.helper"
              - "@table_action.helper"


    kelp.type_storage.delete.listener:
            class: Kelp\AppBundle\EventListener\DeleteTypeStorageListener
            arguments:
              - "@=service('kelp.mapper_manager').getDefaultMapperFor('type_storage')"
              - "@=service('request_stack').getCurrentRequest()"
