services:
    kelp.user.doctrine.mapper:
        class: Kelp\AppBundle\Mapper\UserDoctrineMapper
        public: false
        arguments: ["@doctrine", "KelpAppBundle:User"]
        tags: [{name: "kelp_app.mapper", type: "doctrine", class: "user"}]

    kelp.type_storage.doctrine.mapper:
        class: Kelp\AppBundle\Mapper\TypeStorageDoctrineMapper
        public: false
        arguments:
          - "@doctrine"
          - "KelpAppBundle:TypeStorage"
          - "@kelp.type_storage.factory"
        tags: [{name: "kelp_app.mapper", type: "doctrine", class: "type_storage"}]


    kelp.user_type_storage.doctrine.mapper:
        class: Kelp\AppBundle\Mapper\UserTypeStorageDoctrineMapper
        public: false
        arguments:
          - "@doctrine"
          - "KelpAppBundle:TypeStorage"
          - "@kelp.user_type_storage.factory"
        tags: [{name: "kelp_app.mapper", type: "doctrine", class: "user_type_storage"}]