services:
    kelp.type_storage.processor:
        class: Kelp\AppBundle\Processor\SettingTypeStorageProcessor
        arguments:
          - "@event_dispatcher"
          - "@=service('request_stack').getCurrentRequest()"

    kelp.user.processor:
        class: Kelp\AppBundle\Processor\SettingUserProcessor
        arguments:
          - "@event_dispatcher"
          - "@=service('request_stack').getCurrentRequest()"