services:
    kelp.home.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor

    kelp.type_storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.type_storage.search_form.listener']]
          - ['addSubscriber', ['@kelp.type_storage.add_form.listener']]

    kelp.add.type_storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.type_storage.add_form.listener']]

    kelp.add.storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.storage.add_form.listener']]

    kelp.delete.type_storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.type_storage.delete.listener']]

    kelp.delete.user.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.user.delete.listener']]

    kelp.find.type_storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.type_storage.find.listener']]

    kelp.edit.type_storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.type_storage.edit_form.listener']]

    kelp.user.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls: [['addSubscriber', ['@kelp.user.search_form.listener']]]

    kelp.dashboard.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.dashboard.listener']]
          - ['addSubscriber', ['@kelp.user_type_storage.edit_form.listener']]
          - ['addSubscriber', ['@kelp.storage.add_form.listener']]

    kelp.edit.user_type_storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.user_type_storage.edit_form.listener']]

    kelp.delete.storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.storage.delete.listener']]

    kelp.edit.storage.processor:
        class: Kelp\AppBundle\Processor\GenericProcessor
        calls:
          - ['addSubscriber', ['@kelp.storage.edit_form.listener']]