version: '3.3'
services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kelp
        ports:
          - "127.0.0.1:3316:3306"
        volumes:
          - database:/var/lib/mysql
    app:
        image: dockerphp/nginx:7.2-stretch
        links:
            - db
        volumes:
            - .:/app
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "127.0.0.1:8003:80"
    pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
          - "127.0.0.1:8001:80"
volumes:
  database: ~
