version: '3.3'
services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kelp
            MYSQL_USER: kelp
            MYSQL_PASSWORD: symfony
    app:
        image: dockerphp/nginx:7.2-stretch
        links:
            - db
        volumes:
            - .:/app
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "443:443"
    pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
          - 8080:80