kelp.storage.list:
    path: /storage
    controller: App\Controller\StorageController::listAction

kelp.storage.create:
    path: /storage/create/{id}
    controller: App\Controller\StorageController::createAction
    requirements:
        id: '\d+'

kelp.storage.edit:
    path: /storage/edit/{id}
    controller: App\Controller\StorageController::editAction
    requirements:
        id: '\d+'

kelp.storage.delete:
    path: /storage/delete/{id}
    controller: App\Controller\StorageController::deleteAction
    requirements:
            id: '\d+'