app:
  resource: 'Routing/setting_type_storage.yml'
  prefix:   /setting

kelp_app_homepage:
    path:     /
    defaults: { _controller: KelpAppBundle:Dashboard:index }

kelp_setting_user:
    path:     /setting/user
    defaults: { _controller: KelpAppBundle:Setting:user }
