kelp.home:
    path:     /
    defaults:
        _controller: KelpAppBundle:Generic:view
        element: "home"

dashboard:
  resource: 'Routing/dashboard.yml'
  prefix:   /dashboard

setting:
  resource: 'Routing/setting.yml'
  prefix:   /setting
